/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,html}'],
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1b',
        'surface-container': '#1f1f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        'surface-variant': '#353535',
        'surface-tint': '#c6c6c7',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#c4c7c8',
        'on-background': '#e2e2e2',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        outline: '#8e9192',
        'outline-variant': '#444748',
        primary: '#e2e2e2',
        'on-primary': '#2f3131',
        'primary-container': '#929394',
        'on-primary-container': '#636565',
        'inverse-primary': '#5d5f5f',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#454747',
        secondary: '#fe5f02',
        'on-secondary': '#5a1c00',
        'secondary-container': '#fe5f02',
        'on-secondary-container': '#521900',
        'secondary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#ffb599',
        'on-secondary-fixed': '#370e00',
        'on-secondary-fixed-variant': '#7f2b00',
        tertiary: '#0097ff',
        'on-tertiary': '#00325a',
        'tertiary-container': '#0097ff',
        'on-tertiary-container': '#002e53',
        'tertiary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#a0c9ff',
        'on-tertiary-fixed': '#001c37',
        'on-tertiary-fixed-variant': '#00497f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-tv': '80px',
        'gutter-tv': '40px',
        'margin-admin': '32px',
        'gutter-admin': '24px',
      },
      fontFamily: {
        'display-tv': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-tv': ['72px', { lineHeight: '84px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['24px', { lineHeight: '36px', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
      },
      boxShadow: {
        'focus-glow': '0 0 20px 2px rgba(0, 218, 243, 0.3)',
        'focus-glow-secondary': '0 0 20px 2px rgba(254, 95, 2, 0.3)',
      },
    },
  },
  plugins: [],
};
